name = "paper-agent-project"
main = "src/index.ts"
compatibility_date = "2026-05-03"

[[d1_databases]]
binding = "DB"
database_name = "paper_agent_db"
database_id = "4d622431-3574-4e04-a359-dada93e97438"

[[r2_buckets]]
binding = "REPORTS"
<<<<<<< HEAD
bucket_name = "paper-agent-outputs"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "paper-abstract-index"
=======
bucket_name = "paper-agent-outputs"
>>>>>>> origin/main
